name: Process Artisan Commands
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
  plugin:
    name: Laravel Version ${{ matrix.laravel }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        laravel: [6.x, 7.x, 8.x]
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Install Laravel
        run: composer create-project --no-progress laravel/laravel="${{ matrix.laravel }}" /tmp/laravel

      - name: Build command file
        run: |
          cd /tmp/laravel
          cat ${{ github.workspace }}/build | php artisan tinker > ${{ github.workspace }}/static/${{ matrix.laravel }}.json | true

      - name: Set up git user
        run: git config --global user.name ${GITHUB_ACTOR}

      - name: Set up git email
        run: git config --global user.name ${GITHUB_ACTOR}@users.noreply.github.com

      - name: Commit comand files if needed #it fails if nothing has changed so we allow an error
        run: git add -A && git commit -am 'Build commands' && git push
        continue-on-error: true
