name: Process Artisan Commands
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
  plugin:
    name: Laravel Version ${{ matrix.laravel }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        laravel: [7.x, 8.x]
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: mbstring, dom, fileinfo
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Install Laravel
        run: composer create-project laravel/laravel="${{ matrix.laravel }}" /tmp/laravel
      - name: Build command file
        run: |
          cd /tmp/laravel
          more ${{ github.workspace }}/build | php artisan tinker > ${{ github.workspace }}/static/${{ matrix.laravel }}.json
          ls -la ${{ github.workspace }}/static
